export const posts = [
    {
        id: 1,
        title: "5Premium Theme for React",
        img: "https://images.pexels.com/photos/5720783/pexels-photo-5720783.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ipsam ullam perferendis nesciunt, natus voluptas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ipsam ullam perferendis nesciunt, natus voluptas. ",
        longDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem"
    },
    {
        id: 2,
        title: "How to animate Elements",
        img: "https://images.pexels.com/photos/11163123/pexels-photo-11163123.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ipsam ullam perferendis nesciunt, natus voluptas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ipsam ullam perferendis nesciunt, natus voluptas.",
        longDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem."
    },
    {
        id: 3,
        title: "Learn JS in 3days",
        img: "https://images.pexels.com/photos/4224255/pexels-photo-4224255.jpeg?auto=compress&cs=tinysrgb&w=1200&lazy=load",
        desc: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ipsam ullam perferendis nesciunt, natus voluptas.  Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ipsam ullam perferendis nesciunt, natus voluptas.",
        longDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatemLorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta explicabo possimus suscipit ea ipsam nihil, earum esse, nam culpa debitis, eum tenetur voluptates. Ullam sint doloribus qui voluptatum odio voluptatem."
    },
] 